apiVersion: v1
kind: Pod
metadata:
  name: pod-hostpath
  namespace: audit-zone
spec:
  containers:
    - name: nginx
      image: nginx:stable
      volumeMounts:
        - name: host-logs
          mountPath: /host/varlog
  volumes:
    - name: host-logs
      hostPath:
        path: /var/log
        type: Directory
